# Generated by Django 5.2.5 on 2025-08-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_listtask_description_task_unique_task_order_per_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_order_per_list',
        ),
    ]
